config-graph:
  startup:
    disk-loader:
      paths: config-graph

spring:
  cache:
    cache-names: aclSpelExpressions
    caffeine:
      spec: expireAfterAccess=3600s

  profiles:
    active: provider-hazelcast