config-graph:
  startup:
    disk-loader:
      paths: config-graph

spring:
  cache:
    cache-names: aclSpelExpressions
    caffeine:
      spec: expireAfterAccess=3600s

  datasource:
    url: "jdbc:mysql://host:3306/db"
    username: user
    password: pw
    # Customize Hikari connection pool behavior
    hikari:
      minimumIdle: 1
      maximumPoolSize: 8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          hazelcast:
            configuration_file_path: ${portal.home}/config-graph-hz.xml
          region:
            factory_class: com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory
        temp:
          use_jdbc_metadata_defaults: false